### ISSUE TITLE
Consider adding all schemas/models for websocket/user-data streams

### ISSUE THREAD

**Issue by DartMen** [binance-exchange/binance-api-swagger#6]
Right now only Aggregate Trade Streams (aggTrade) seems partly included, but misses the e, E and s.

Please add all schemas/models from the following documents:

https://github.com/binance/binance-spot-api-docs/blob/master/user-data-stream.md
https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md

**Comment by aisling11** [comment]
Hi @DartMen, sorry for the late reply on this. This project is set for REST API endpoints only, so the _aggTrade_ schema you see in the file is in for the `api/v3/aggTrades` endpoint and therefore "e, E and s" fields are not shown.
We'll highlight this in a newer README.md file in the near future :) Closing this issue for now.
